### ISSUE TITLE
Typo for Prereq

### ISSUE THREAD

**Issue by mwdarab** [microsoft/sqlworkshops-bdc#1]
https://github.com/microsoft/sqlworkshops-bdc/blob/master/SQL2019BDC/00%20-%20Prerequisites.md

Under **Activity 2: Prepare Your Workstation**

It still says "4**MB** of RAM" instead of "4**GB** of RAM".

**Comment by BuckWoody** [comment]
Thanks for the catch! Can't believe I put that BACK in after I corrected it last time. :)
