### ISSUE TITLE
Region error for downloading BDC deployment script

### ISSUE THREAD

**Issue by matthewburrows-msft** [microsoft/sqlworkshops-bdc#3]
When downloading the deployment script at <https://docs.microsoft.com/en-us/sql/big-data-cluster/quickstart-big-data-cluster-deploy?view=sqlallproducts-allversions#download-the-deployment-script>, I get the error message "The provided location is not available for resource group."

Possible reason for error: It may be an issue related to region.  At first, I tried typing “ENTER” to use the default ‘westus’ region.  After seeing the first error message, I retried using the ‘westcentralus’ region but still received a similar error message.  This might also be an issue specific to my Azure account, in which case you can close this issue.

**Comment by BuckWoody** [comment]
Not able to repo that - also, I would ensure you are doing this from an on-prem system as described in the instructions. If you are using a Cloud Shell, we have not tested that. 

Peace! And thanks for the review. :)
